project:
  type: website
  
website:
  title: "Brian Calhoon"
  site-url: "https://dabrianc.github.io/website/"
  description: "Data analysis with R programming language and more"
  navbar:
    right:
      - dc_ski_resorts_state_filter.qmd
      - blog.qmd
      - icon: github
        href: https://github.com/DABrianC
      - icon: linkedin
        href: https://linkedin.com/in/brian-calhoon/
    search: true
format:
  html:
    feed: 
      type: xml
      file: index.xml
      title: "Humans Learning"
      description: "Data analysis with R programming language and more"
      language: en
      categories: [R]
    theme:
      - sandstone
      - brand
    css: styles.css

permissions:
  contents: read
  pages: write
  id-token: write
  
editor: visual

